name: Sync upstream

on:
  schedule:
    - cron: "23 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
      - name: Merge upstream dev
        run: |
          git remote add upstream https://github.com/ProtonMail/gluon.git
          git fetch upstream dev
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git merge --no-edit upstream/dev
          git push origin HEAD:dev
